### PR TITLE
[WIP] Update for macOS Mojave

### PR DESCRIPTION
**Pull request by saagarjha**
(Continued from #5)

So the code I have here is very much *not* meant to be safe at all. I tried to make it work on as many versions of Dock as possible, which is why I'm only searching for bits and pieces in the hope that it will continue to work even if the function is modified slightly. My program has continued to work through a couple of updates of Mojave, but this might just be because the Apple has not changed this function or updated the compiler significantly (thank goodness for "-Os", which generally doesn't make crazy changes anyways).

If you're serious about merging this, there are a couple options. What is currently happening is that there is a (Swift, presumably) function that takes in a `Bool`–whether the bar is collapsed–and then passes that parameter into another function. What forceFullDesktopBar is doing is trying to find the prologue to that function, then right before `$rcx` (which holds this value for the second call) is loaded off the stack we instead just zero it out with an equivalently sized `xor rcx,rcx` instead so we always keep it expanded. So this can break in a multitude of ways: we could just match the wrong function at some point if it has the same prologue and shows up earlier at some point, in which case we will likely overwrite some other code and cause a crash. We could also "run off the end" of the function in looking for the code to overwrite, since we don't know how long it is, which could be the case if the function changes or the order of the parameters changes. So overall, not very stable stuff. Assuming we can't find another way to override this that's safe (for example, using the Objective-C runtime or even mach_override), there are a couple of options I think might be safer:

* Your method, essentially looking for the entire function contents "to be sure" and then overwriting the part we care about.
* Doing the above, and if we can't find the function, presenting an alert asking the user if we want to try the current, unsafe method as a workaround.
* Installing a signal handler that detects crashes, writes a preferences somewhere, and will stop us from continually trying to load a broken forceFullDesktopBar and entering a crashloop.

### CODE REVIEW

**Comment by briankendall** [comment]
So I don't think using the Objective-C runtime is an option any longer since not very much of the Dock is Objective-C. (Though if we could find a new function to swizzle that would be ideal, but I've never been able to find one.) It doesn't look like Swift provides any kind of similar facility. Apparently the Swift compiler tries to handle as much as possible at compile time, hence most of these methods compiling down to anonymous functions.

So let's consider mach_override. We'd still need to find the address of the function to override, but it'd let us more easily mess with what parameters are being passed into it without having to manually patch any code. Maybe we could do a similar search to what you're already doing to find the address of the first function (the one that takes a bool that specifies if the bar is collapsed) and override it with a function that just calls into the original one with the right bool value. If I understand what this PR is doing, maybe it's also possible to override the second function too, and that could be a preferable option depending on which one is more likely to change between macOS updates. My experience with mach_override is pretty limited though... do you think that would be better than manually patching?

Either way, while I think we can figure out a relatively safe method of doing the patch mainly by only matching functions we know are the ones we want by doing very specific searches (and the other suggestions you made are good too). The issue then is that forceFullDesktopBar might need an update every time Apple updates the Dock, and that update could require redoing the same sort of reverse engineering you've already done. I'm still pretty new to this level of reverse engineering and am not great at dealing with assembler, so if I were going to continue to maintain the project I'd either need to learn or rely on you. How much work was it for you to find the function that you're patching?

**Comment by saagarjha** [comment]
> So I don't think using the Objective-C runtime is an option any longer since not very much of the Dock is Objective-C. (Though if we could find a new function to swizzle that would be ideal, but I've never been able to find one.) It doesn't look like Swift provides any kind of similar facility. Apparently the Swift compiler tries to handle as much as possible at compile time, hence most of these methods compiling down to anonymous functions.

So there do seem to be Objective-C functions in the binary the look useful, but I can never seem to get them to do anything. I'm not sure what's happening here, but I have a suspicion that the Swift compiler is eliding the actual message send and directly calling the function since it can "prove" that they are never called dynamically. I still refuse to believe that Apple is shipping a binary with functions that are never called. Either way, there's not much we can do here with swizzling, I think.

> So let's consider mach_override. We'd still need to find the address of the function to override, but it'd let us more easily mess with what parameters are being passed into it without having to manually patch any code. Maybe we could do a similar search to what you're already doing to find the address of the first function (the one that takes a bool that specifies if the bar is collapsed) and override it with a function that just calls into the original one with the right bool value. If I understand what this PR is doing, maybe it's also possible to override the second function too, and that could be a preferable option depending on which one is more likely to change between macOS updates. My experience with mach_override is pretty limited though... do you think that would be better than manually patching?

Yes, exactly, that's what I was thinking of: we find the function pointer (either function should be fine) through our technique and just pass it to mach_override. Then the only thing that should break is that the function goes missing (which we can detect, hopefully) or the calling convention changes (which we can't) or mach_override itself breaks. Speaking of which, apparently it's currently broken for 64-bit since 10.13, but as Chromium relies on it they basically just keep it up-to-date so this shouldn't be much of a problem. The benefit of using this is we no longer have to deal with these little twiddly hacks where I try to compete with the compiler in terms of size-constrained code, because mach_override just copies the entire function out to somewhere else and overwrites the the original location with a trampoline to the overridden implementation so there's no size limit.

> Either way, while I think we can figure out a relatively safe method of doing the patch mainly by only matching functions we know are the ones we want by doing very specific searches (and the other suggestions you made are good too). The issue then is that forceFullDesktopBar might need an update every time Apple updates the Dock, and that update could require redoing the same sort of reverse engineering you've already done. I'm still pretty new to this level of reverse engineering and am not great at dealing with assembler, so if I were going to continue to maintain the project I'd either need to learn or rely on you. How much work was it for you to find the function that you're patching?

Finding this method for the first time was a horrible, horrible process that took forever and I really don't want to have to repeat again. Essentially it just consisted of me repeatedly invoking Mission Control with and without my mouse at the top of the screen and looking through Dock's call stack to find a function that seemed to have a boolean parameter that changed in response. With regards to maintaining it, there are couple of things that couple happen:

* Apple doesn't change the function at all, but updates the Dock binary: Most likely the offset of this function might change, but we account for that because we're searching through the binary anyways due to ASLR.
* Apple changes the function slightly: Most likely it shouldn't be too difficult to find this function again; there are a couple of strings ("com.apple.springing.delay", "SpacesWindowBarController") that are referenced in the functions that aren't used anywhere else so this can be used as a marker.
* Apple rewrites significantly: Then I guess we're going to have to do this all again. I'm looking into tools to automate this sort of analysis; I'm not sure if they exist but if they don't I might end up writing them.

**Comment by MRIO** [comment]
Just wanted to say that it's brilliant that you two are even looking into this! Kudos for persistence and tenacity!

**Comment by saagarjha** [comment]
This has been bothering me for over two years, so I guess you could say that it's important to me that this works ;)

**Comment by briankendall** [comment]
> So there do seem to be Objective-C functions in the binary the look useful, but I can never seem to get them to do anything. I'm not sure what's happening here, but I have a suspicion that the Swift compiler is eliding the actual message send and directly calling the function since it can "prove" that they are never called dynamically. I still refuse to believe that Apple is shipping a binary with functions that are never called. Either way, there's not much we can do here with swizzling, I think.

I was quite confused by that too! But I think your explanation makes sense.

> Finding this method for the first time was a horrible, horrible process that took forever and I really don't want to have to repeat again. Essentially it just consisted of me repeatedly invoking Mission Control with and without my mouse at the top of the screen and looking through Dock's call stack to find a function that seemed to have a boolean parameter that changed in response.

I suspected as much. That's quite a lot of dedication! I tried that for a few hours before giving up. Hopefully you won't have to do that sort of thing again.

> With regards to maintaining it, there are couple of things that couple happen:
> * Apple doesn't change the function at all, but updates the Dock binary: Most likely the offset of this function might change, but we account for that because we're searching through the binary anyways due to ASLR.

I'm hoping this is what will happen most of the time we see a minor macOS update.

> * Apple changes the function slightly: Most likely it shouldn't be too difficult to find this function again; there are a couple of strings ("com.apple.springing.delay", "SpacesWindowBarController") that are referenced in the functions that aren't used anywhere else so this can be used as a marker.

Good point on the markers. I was just looking at the 10.12.6 and 10.13.6 version of the Dock and it looks like we can use those to find the earlier versions of those same functions. Since I'd prefer forceFullDesktopBar to not have a big gap in which versions of macOS it supports (only supporting 10.11 and 10.14 would be quite odd) I'm thinking that this would be a good way to get a sense whether updates to the Dock may be easy to deal with by seeing how hard it is to get it working in 10.12 and/or 10.13. We'll need to be able to have the app search for one of many possible functions anyway. (Note though that between 10.12 and 10.13 the functions have slightly different signatures, so we'll need to be able to accommodate that.)

> * Apple rewrites significantly: Then I guess we're going to have to do this all again. I'm looking into tools to automate this sort of analysis; I'm not sure if they exist but if they don't I might end up writing them.

That sounds like quite the undertaking but I'll certainly encourage you to try. Anything to make it easier to hack macOS 😉. At the very least we're right at the beginning of 10.14 so I think it's quite unlikely we'll see any huge changes happen to the Dock until a year from now when 10.15 comes out.

It seems like we're in agreement about how to proceed with this with mach_inject. Would you like to take a first pass at this? I *may* have some time in the next week or so to work on this but I'm not sure precisely when. If you can get a version working in 10.14 using mach_inject I could try seeing about expanding it to work in 10.12 and 10.13. (I'm not sure what the best way of collaborating on GitHub will be though since as I understand it only you will be able to make commits to this PR.)

**Comment by saagarjha** [comment]
I've migrated the code to mach_override in the latest commit. Since you're a maintainer of this project, you should be able to push to `master` for [my repository](https://github.com/briankendall/forceFullDesktopBar/tree/master). If you're feeling up to it, you can try adding in the functions for 10.13 and 10.12 in dockInjection.h–otherwise, you can just send me the binaries and I can do it myself.

**Comment by briankendall** [comment]
Just checked out your latest commits and was able to easily modify them to get it working in 10.14.0. However... I'm sad to report that both functions we're looking to find and patch are slightly modified between 10.14.0 and 10.14.1 beta 2. So I think that means we can expect to need to update forceFullDesktopBar every time there's a minor release of macOS. That's annoying but not too bad since the functions are easy to find, at least for now.

That said, I wonder what methods if any there are for trying to find the address of these functions in a more robust way? In theory it would be possible to search through the Dock's strings and find the addresses of both `com.apple.springing.delay` and `SpacesWindowBarController`, search for the functions that references both of those strings, confirm that the function that references `com.apple.springing.delay` calls into the function that references `SpacesWindowBarController`, and then ensure the signatures of the functions match what we think they are. But I barely have any idea how to go about implementing such a thing. And I wonder if there are other methods?

**Comment by briankendall** [comment]
I may have found a stable way of updating forceFullDesktopBar that doesn't involve using mach_override. See my latest comment in #5 for more information. While I'm optimistic about it, I sort of feel bad at the same time because that method wouldn't make use of the fabulous work you've done in this PR. (Though that could be used to get the app working in macOS 10.12.)

**Comment by saagarjha** [comment]
I'm fine with whatever makes forceFullDesktopBar work. We can keep this around in case the method you're swizzling disappears.

**Pull request closed without merging**
